// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/isaias-dgr/stori-balance/src/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: dest, acc
func (_m *Mailer) Send(dest string, acc domain.Account) error {
	ret := _m.Called(dest, acc)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Account) error); ok {
		r0 = rf(dest, acc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMailer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMailer(t mockConstructorTestingTNewMailer) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
